/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaUnoIPC2.InterfazGrafica;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import practicaUnoIPC2.enums.MetodoPago;
import practicaUnoIPC2.enums.TipoEvento;
import practicaUnoIPC2.enums.TipoParticipante;
import practicaUnoIPC2.logica.EventoLogica;
import practicaUnoIPC2.logica.PagoLogica;
import practicaUnoIPC2.logica.ParticipanteLogica;
import practicaUnoIPC2.logica.ReporteLogica;
import practicaUnoIPC2.logica.Validador;
import practicaUnoIPC2.modelo.Evento;
import practicaUnoIPC2.modelo.Pago;
import practicaUnoIPC2.modelo.Participante;

/**
 *
 * @author aguil
 */
public class InterfazGrafica extends javax.swing.JFrame {

    

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        areaSalida = new javax.swing.JTextArea(8, 60);
        areaSalida.setEditable(false);
        areaSalida.setLineWrap(true);
        areaSalida.setWrapStyleWord(true);
        scrollSalida = new javax.swing.JScrollPane(areaSalida);
        getContentPane().add(scrollSalida, java.awt.BorderLayout.SOUTH);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        GuardarDatos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArchivoMenu = new javax.swing.JMenu();
        CargarArchivo = new javax.swing.JMenuItem();
        SeleccionarArchivo = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        OperacionesMenu = new javax.swing.JMenu();
        AbrirOperacion = new javax.swing.JMenuItem();
        ReporteMenu = new javax.swing.JMenu();
        ReporteParticipante = new javax.swing.JMenuItem();
        ReporteActividad = new javax.swing.JMenuItem();
        ReporteEventos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        GuardarDatos.setText("Guardar Datos");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });

        ArchivoMenu.setText("Archivo");

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        ArchivoMenu.add(CargarArchivo);

        SeleccionarArchivo.setText("Seleccionar Archivo");
        SeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarArchivoActionPerformed(evt);
            }
        });
        ArchivoMenu.add(SeleccionarArchivo);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        ArchivoMenu.add(Salir);

        jMenuBar1.add(ArchivoMenu);

        OperacionesMenu.setText("Operaciones");
        OperacionesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacionesMenuActionPerformed(evt);
            }
        });

        AbrirOperacion.setText("Abrir Operaciones");
        AbrirOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirOperacionActionPerformed(evt);
            }
        });
        OperacionesMenu.add(AbrirOperacion);

        jMenuBar1.add(OperacionesMenu);

        ReporteMenu.setText("Reportes");

        ReporteParticipante.setText("Participantes");
        ReporteParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteParticipanteActionPerformed(evt);
            }
        });
        ReporteMenu.add(ReporteParticipante);

        ReporteActividad.setText("Actividad");
        ReporteActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActividadActionPerformed(evt);
            }
        });
        ReporteMenu.add(ReporteActividad);

        ReporteEventos.setText("Eventos");
        ReporteEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteEventosActionPerformed(evt);
            }
        });
        ReporteMenu.add(ReporteEventos);

        jMenuBar1.add(ReporteMenu);

        jMenu4.setText("Ventana");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Acerca de");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuardarDatos)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void SeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarArchivoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

  ReporteLogica logica = new ReporteLogica();   
ParticipanteLogica participanteLogica = new ParticipanteLogica();
    private void ReporteParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteParticipanteActionPerformed
      JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar reporte de Participantes");
    int seleccion = chooser.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();
        
        ReporteLogica logica = new ReporteLogica();
        boolean ok = logica.reporteParticipantes(
            archivo.getParent(), 
            "EVT001",            
            null,                
            null                 
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Reporte de participantes generado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de participantes.");
        }
    }
    }//GEN-LAST:event_ReporteParticipanteActionPerformed

    PagoLogica pagoLogica = new PagoLogica();
     
    private void ReporteActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActividadActionPerformed
       JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar reporte de Actividades");
    int seleccion = chooser.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();

        ReporteLogica logica = new ReporteLogica();
        boolean ok = logica.reporteActividades(
            archivo.getParent(), 
            "EVT001", // ID del evento
            null,     // filtro tipoActividad
            null      // filtro correo encargado
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Reporte de actividades generado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de actividades.");
        }
    }
    }//GEN-LAST:event_ReporteActividadActionPerformed

   
    EventoLogica eventoLogica = new EventoLogica();
    private void ReporteEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteEventosActionPerformed
       JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar reporte de Eventos");
    int seleccion = chooser.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();

        ReporteLogica logica = new ReporteLogica();
        boolean ok = logica.reporteEventos(
            archivo.getParent(),
            null, // tipoEvento
            null, // fechaInicio
            null, // fechaFin
            null, // cupoInicial
            null  // cupoFinal
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Reporte de eventos generado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de eventos.");
        }
    }
    }//GEN-LAST:event_ReporteEventosActionPerformed

    private void OperacionesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacionesMenuActionPerformed

    }//GEN-LAST:event_OperacionesMenuActionPerformed

    private void AbrirOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirOperacionActionPerformed
        VentanaInterna vi = new VentanaInterna();
        jDesktopPane1.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_AbrirOperacionActionPerformed

    // Variables de clase
    private javax.swing.JTextArea areaSalida;
    private javax.swing.JScrollPane scrollSalida;


    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed
        areaSalida.setText("");

        String input = jTextArea1.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar datos.");
            return;
        }

        String[] lineas = input.split("\\r?\\n");
        for (String linea : lineas) {
            linea = linea.trim();
            if (linea.isEmpty()) {
                continue;
            }

            try {
                // Ejemplo: REGISTRO_EVENTO("EVT-00000001","25/08/2025","CHARLA","Tema","Ubicacion",150,50.00);
                String instruccion = linea.substring(0, linea.indexOf("(")).trim();
                String parametros = linea.substring(linea.indexOf("(") + 1, linea.lastIndexOf(")"));
                // Quitar comillas y espacios
                String[] args = parametros.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");
                for (int i = 0; i < args.length; i++) {
                    args[i] = args[i].trim().replaceAll("^\"|\"$", ""); // quitar comillas
                }

                switch (instruccion.toUpperCase()) {
                    case "REGISTRO_EVENTO": {
                        Evento e = new Evento();
                        e.setId_evento(args[0]);
                        e.setFecha(Validador.parseFechaDDMMYYYY(args[1]));
                        e.setTipo_evento(Validador.safeEnum(TipoEvento.class, args[2]));
                        e.setTitulo_evento(args[3]);
                        e.setUbicacion(args[4]);
                        e.setCupo_maximo_evento(Integer.parseInt(args[5]));
                        e.setCosto(new java.math.BigDecimal(args[6]));

                        EventoLogica el = new EventoLogica();
                        if (el.crearEvento(e)) {
                            areaSalida.append(" Evento registrado: " + e.getId_evento() + "\n");
                        } else {
                            areaSalida.append(" Error al registrar evento: " + e.getId_evento() + "\n");
                        }
                        break;
                    }

                    case "REGISTRO_PARTICIPANTE": {
                        Participante p = new Participante();
                        p.setNombreCompleto(args[0]);
                        p.setTipoParticipante(Validador.safeEnum(TipoParticipante.class, args[1]));
                        p.setInstitucion(args[2]);
                        p.setCorreo(args[3]);

                        ParticipanteLogica pl = new ParticipanteLogica();
                        if (pl.crearParticipante(p)) {
                            areaSalida.append("✔ Participante registrado: " + p.getCorreo() + "\n");
                        } else {
                            areaSalida.append("❌ Error al registrar participante: " + p.getCorreo() + "\n");
                        }
                        break;
                    }

                    case "REGISTRO_PAGO": {
                        Pago pago = new Pago();
                        pago.setCorreo(args[0]);
                        pago.setId_evento(args[1]);
                        pago.setMonto(new java.math.BigDecimal(args[2]));
                        pago.setMetodo_pago(Validador.safeEnum(MetodoPago.class, args[3]));

                        PagoLogica pagL = new PagoLogica();
                        if (pagL.registrarPago(pago)) {
                            areaSalida.append(" Pago registrado: " + pago.getCorreo() + "\n");
                        } else {
                            areaSalida.append(" Error al registrar pago: " + pago.getCorreo() + "\n");
                        }
                        break;
                    }

                    default:
                        areaSalida.append(" Instrucción no reconocida: " + instruccion + "\n");
                }
            } catch (Exception ex) {
                areaSalida.append(" Error procesando línea: " + linea + " → " + ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_GuardarDatosActionPerformed

    public void Menu() {
        JMenuItem abrir = new JMenuItem("Abrir archivo de entrada");
        abrir.addActionListener(e -> abrirArchivoEntrada());

        JMenuItem configurarDelay = new JMenuItem("Configurar delay");
        configurarDelay.addActionListener(e -> configurarDelay());

        JMenuItem configurarSalida = new JMenuItem("Configurar ruta de salida");
        configurarSalida.addActionListener(e -> configurarSalida());

        ArchivoMenu.add(abrir);
        ArchivoMenu.add(configurarDelay);
        ArchivoMenu.add(configurarSalida);

    }

    private void abrirArchivoEntrada() {
        JFileChooser chooser = new JFileChooser();
        int seleccion = chooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            jTextArea1.setText("Archivo cargado: " + archivo.getAbsolutePath());
            // Aquí ya puedes procesar el archivo con tus clases de lógica
        }
    }

    private void configurarDelay() {
        String input = JOptionPane.showInputDialog(this, "Ingrese el delay en segundos:");
        try {
            int delay = Integer.parseInt(input);
            jLabel1.setText("Delay: " + delay + "s");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número inválido");
        }
    }

    private void configurarSalida() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = chooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File directorio = chooser.getSelectedFile();
            jLabel1.setText("Ruta de salida: " + directorio.getAbsolutePath());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirOperacion;
    private javax.swing.JMenu ArchivoMenu;
    private javax.swing.JMenuItem CargarArchivo;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JMenu OperacionesMenu;
    private javax.swing.JMenuItem ReporteActividad;
    private javax.swing.JMenuItem ReporteEventos;
    private javax.swing.JMenu ReporteMenu;
    private javax.swing.JMenuItem ReporteParticipante;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem SeleccionarArchivo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
